#!/bin/bash

FILE=$1
if [ "$FILE" == "" ]; then
    echo "Please provide the path to the template file";
    exit 1;
fi

cat "$FILE" | envsubst $(list='';for var in $(env); do list=$list"\${$(echo $var | cut -d '=' -f1)}"; done; echo $list)
