#!/bin/bash

if test -d ~/.config/i3/startup.d; then
    for entry in ~/.config/i3/startup.d/*; do
        logger "[i3 startup] loading ${entry##*/}";
        . "$entry";
        logger "[i3 startup] loaded ${entry##*/}";
    done
fi
