#!/bin/bash
display=$(xrandr | grep primary | awk '{ print $1 }')

if xrandr --listmonitors | grep "$display" > /dev/null; then
  xrandr --output "$display" --off
else
  xrandr --output "$display" --auto
fi
